TebLocalPlannerROS:

 odom_topic: odom
 map_frame: /map
    
 # Trajectory  
 teb_autosize: True # Enable the automatic resizing of the trajectory during optimization (based on the temporal resolution of the trajectory, recommended
 dt_ref: 0.3 # Temporal resolution of the planned trajectory (usually it is set to the magnitude of the 1/control_rate)
 dt_hysteresis: 0.1 # Hysteresis that is utilized for automatic resizing depending on the current temporal resolution (dt): usually 10% of dt_ref
 global_plan_overwrite_orientation: True # Some global planners are not considering the orientation at local subgoals between start and global goal, therefore determine it automatically
 allow_init_with_backwards_motion: False # If true, the underlying trajectories might be initialized with backwards motions in case the goal is behind the start within the local costmap (this is only recommended if the robot is equipped with rear sensors)
 max_global_plan_lookahead_dist: 3.0 # Specify maximum length (cumulative Euclidean distances) of the subset of the global plan taken into account for optimization [if 0 or negative: disabled; the length is also bounded by the local costmap size]
 force_reinit_new_goal_dist: 1.0 # Force the planner to reinitialize the trajectory if a previous goal is updated with a seperation of more than the specified value in meters (skip hot-starting)
 force_reinit_new_goal_angular: 0.78 # Force the planner to reinitialize the trajectory if a previous goal is updated with a rotational difference of more than the specified value in radians (skip hot-starting)
 feasibility_check_no_poses: 3 # Specify up to which pose (under the feasibility_check_lookahead_distance) on the predicted plan the feasibility should be checked each sampling interval; if -1, all poses up to feasibility_check_lookahead_distance are checked.
 feasibility_check_lookahead_distance: -1 # Specify up to which distance (and with an index below feasibility_check_no_poses) from the robot the feasibility should be checked each sampling interval; if -1, all poses up to feasibility_check_no_poses are checked.
 exact_arc_length: False # If true, the planner uses the exact arc length in velocity, acceleration and turning rate computations [-> increased cpu time], otherwise the euclidean approximation is used.
 publish_feedback: True # Publish planner feedback containing the full trajectory and a list of active obstacles (should be enabled only for evaluation or debugging purposes)
 control_look_ahead_poses: 3 # Index of the pose used to extract the velocity command
 prevent_look_ahead_poses_near_goal: 2 # Prevents control_look_ahead_poses to look within this many poses of the goal in order to prevent overshoot & oscillation when xy_goal_tolerance is very small
 visualize_with_time_as_z_axis_scale: 0 # If this value is bigger than 0, the trajectory and obstacles are visualized in 3d using the time as the z-axis scaled by this value. Most useful for dynamic obstacles.
 
 # ViaPoints
 global_plan_viapoint_sep: 0.4 # Min. separation between each two consecutive via-points extracted from the global plan [if negative: disabled]
 via_points_ordered: False # If true, the planner adheres to the order of via-points in the storage container
 
 # Robot         
 max_vel_x: 0.5 # Maximum translational velocity of the robot
 max_vel_x_backwards: 0.05 # Maximum translational velocity of the robot for driving backwards
 max_vel_theta: 0.5 # Maximum angular velocity of the robot
 acc_lim_x: 1.0 # Maximum translational acceleration of the robot
 acc_lim_theta: 1.0 # Maximum angular acceleration of the robot
 is_footprint_dynamic: False # If true, updated the footprint before checking trajectory feasibility
 use_proportional_saturation: True # If true, reduce all twists components (linear x and y, and angular z) proportionally if any exceed its corresponding bounds, instead of saturating each one individually
 transform_tolerance: 0.5 # Tolerance when querying the TF Tree for a transformation (seconds)
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "line"
   radius: 0.2 # for type "circular"
   line_start: [-0.4, 0.0] # for type "line"
   line_end: [0.4, 0.0] # for type "line"
   front_offset: 0.2 # for type "two_circles"
   front_radius: 0.2 # for type "two_circles"
   rear_offset: 0.2 # for type "two_circles"
   rear_radius: 0.2 # for type "two_circles"
   vertices: [[-1.2, 0.25], [0.5, 0.25], [0.5, -0.25], [-1.2, -0.25]] # for type "polygon"

 # Robot/Car-like
 min_turning_radius: 0.383 # Minimum turning radius of a carlike robot, for the Floribot4.0 actually 0.383 (diff-drive robot: zero)
 wheelbase: 0.766 # The distance between the drive shaft and steering axle (only required for a carlike robot with 'cmd_angle_instead_rotvel' enabled); The value might be negative for back-wheeled robots!
 cmd_angle_instead_rotvel: False # Substitute the rotational velocity in the commanded velocity message by the corresponding steering angle (check 'axles_distance')
 

 # Robot/Omni
 max_vel_y: 0.0 # Maximum strafing velocity of the robot (should be zero for non-holonomic robots!)
 acc_lim_y: 0.0 # Maximum strafing acceleration of the robot

 # GoalTolerance    
 xy_goal_tolerance: 0.1 # Allowed final euclidean distance to the goal position
 yaw_goal_tolerance: 0.05 # Allowed final orientation error to the goal orientation
 free_goal_vel: False # Allow the robot's velocity to be nonzero for planning purposes (the robot can arrive at the goal with max speed)
 trans_stopped_vel: 0.05 # Below what maximum velocity consider we consider the robot to be stopped in translation
 theta_stopped_vel: 0.05 # Below what maximum rotation velocity we consider the robot to be stopped in rotation
    
 # Obstacles    
 min_obstacle_dist: 0.23 # Minimum desired separation from obstacles
 inflation_dist: 0.25 # Buffer zone around obstacles with non-zero penalty costs (should be larger than min_obstacle_dist in order to take effect)
 dynamic_obstacle_inflation_dist: 0.3 # Buffer zone around predicted locations of dynamic obstacles with non-zero penalty costs (should be larger than min_obstacle_dist in order to take effect)
 include_dynamic_obstacles: False # Specify whether the movement of dynamic obstacles should be predicted by a constant velocity model (this also changes the homotopy class search). If false, all obstacles are considered to be static.
 include_costmap_obstacles: True # Specify whether the obstacles in the costmap should be taken into account directly (this is necessary if no seperate clustering and detection is implemented)
 legacy_obstacle_association: False # If true, the old association strategy is used (for each obstacle, find the nearest TEB pose), otherwise the new one (for each teb pose, find only 'relevant' obstacles).
 obstacle_association_force_inclusion_factor: 2.0 # The non-legacy obstacle association technique tries to connect only relevant obstacles with the discretized trajectory during optimization, all obstacles within a specifed distance are forced to be included (as a multiple of min_obstacle_dist), e.g. choose 2.0 in order to consider obstacles within a radius of 2.0*min_obstacle_dist.
 obstacle_association_cutoff_factor: 3.0 # See obstacle_association_force_inclusion_factor, but beyond a multiple of [value]*min_obstacle_dist all obstacles are ignored during optimization. obstacle_association_force_inclusion_factor is processed first.
 costmap_obstacles_behind_robot_dist: 2.0 # Limit the occupied local costmap obstacles taken into account for planning behind the robot (specify distance in meters)
 obstacle_poses_affected: 5 # The obstacle position is attached to the closest pose on the trajectory to reduce computational effort, but take a number of neighbors into account as well

 # Obstacles/Velocity Ratio Parameters
 obstacle_proximity_ratio_max_vel: 1.0 # Ratio of the maximum velocities used as an upper bound when reducing the speed due to the proximity to static obstacles
 obstacle_proximity_lower_bound: 0.0 # Distance to a static obstacle for which the velocity should be lower
 obstacle_proximity_upper_bound: 0.0 # Distance to a static obstacle for which the velocity should be higher


 # Optimization    
 no_inner_iterations: 4 # Number of solver iterations called in each outerloop iteration
 no_outer_iterations: 3 # Each outerloop iteration automatically resizes the trajectory and invokes the internal optimizer with no_inner_iterations
 optimization_activate: True # Activate the optimization
 optimization_verbose: False # Print verbose information
 penalty_epsilon: 0.01 # Add a small safty margin to penalty functions for hard-constraint approximations
 weight_max_vel_x: 2 # Optimization weight for satisfying the maximum allowed translational velocity
 weight_max_vel_y: 0 # Optimization weight for satisfying the maximum allowed strafing velocity (in use only for holonomic robots)
 weight_max_vel_theta: 1 # Optimization weight for satisfying the maximum allowed angular velocity
 weight_acc_lim_x: 1 # Optimization weight for satisfying the maximum allowed translational acceleration
 weight_acc_lim_y: 0 # Optimization weight for satisfying the maximum allowed strafing acceleration (in use only for holonomic robots)
 weight_acc_lim_theta: 1 # Optimization weight for satisfying the maximum allowed angular acceleration
 weight_kinematics_nh: 1000 # Optimization weight for satisfying the non-holonomic kinematics
 weight_kinematics_forward_drive: 1 # (ignored, if min_turning_radius!=0) Optimization weight for forcing the robot to choose only forward directions (positive transl. velocities, only diffdrive robot)
 weight_kinematics_turning_radius: 1 # Optimization weight for enforcing a minimum turning radius (carlike robots)
 weight_optimaltime: 1 # Optimization weight for contracting the trajectory w.r.t. transition time
 weight_shortest_path: 0 # Optimization weight for contracting the trajectory w.r.t. path length
 weight_obstacle: 2 # Optimization weight for satisfying a minimum seperation from obstacles
 weight_inflation: 0.05 # Optimization weight for the inflation penalty (should be small)
 weight_dynamic_obstacle: 0 # Optimization weight for satisfying a minimum seperation from dynamic obstacles
 weight_dynamic_obstacle_inflation: 0 # Optimization weight for the inflation penalty of dynamic obstacles (should be small)
 weight_velocity_obstacle_ratio: 0 # Optimization weight for satisfying a maximum allowed velocity with respect to the distance to a static obstacle
 weight_viapoint: 2 # Optimization weight for minimizing the distance to via-points
 weight_adapt_factor: 2 # Some special weights (currently 'weight_obstacle') are repeatedly scaled by this factor in each outer TEB iteration (weight_new: weight_old * factor); Increasing weights iteratively instead of setting a huge value a-priori leads to better numerical conditions of the underlying optimization problem.
 obstacle_cost_exponent: 1 # Exponent for nonlinear obstacle cost (cost = linear_cost * obstacle_cost_exponent). Set to 1 to disable nonlinear cost (default)
 
 # Homotopy Class Planner
 enable_homotopy_class_planning: True
 enable_multithreading: True # Activate multiple threading for planning multiple trajectories in parallel
 max_number_classes: 3 # Specify the maximum number of allowed alternative homotopy classes (limits computational effort)
 max_number_plans_in_current_class: 2 # Max number of trajectories to try that are in the same homotopy class as the current best trajectory (setting this to 2 or more helps avoid local minima). Must be <= max_number_classes
 selection_cost_hysteresis: 0.9 # Specify how much trajectory cost must a new candidate have w.r.t. a previously selected trajectory in order to be selected (selection if new_cost < old_cost*factor)
 selection_prefer_initial_plan: 0.95 # Specify a cost reduction in the interval (0,1) for the trajectory in the equivalence class of the initial plan.)
 selection_obst_cost_scale: 1.0 # Extra scaling of obstacle cost terms just for selecting the 'best' candidate (new_obst_cost: obst_cost*factor)
 selection_viapoint_cost_scale: 1.0 # Extra scaling of via-point cost terms just for selecting the 'best' candidate. (new_viapt_cost: viapt_cost*factor)
 selection_alternative_time_cost: False # If true, time cost is replaced by the total transition time.
 selection_dropping_probability: 0.1 # At each planning cycle, TEBs other than the current 'best' one will be randomly dropped with this probability. Prevents becoming 'fixated' on sub-optimal alternative homotopies.
 switching_blocking_period: 0.0 # Specify a time duration in seconds that needs to be expired before a switch to new equivalence class is allowed
 roadmap_graph_no_samples: 15 # Specify the number of samples generated for creating the roadmap graph, if simple_exploration is turend off
 roadmap_graph_area_width: 5 # Specify the width of the area in which sampled will be generated between start and goal [m] (the height equals the start-goal distance)
 roadmap_graph_area_length_scale: 1.0 # The length of the rectangular region is determined by the distance between start and goal. This parameter further scales the distance such that the geometric center remains equal!)
 h_signature_prescaler: 0.5 # Scale number of obstacle value in order to allow huge number of obstacles. Do not choose it extremly low, otherwise obstacles cannot be distinguished from each other (0.2<H<=1)
 h_signature_threshold: 0.1 # Two h-signuteres are assumed to be equal, if both the difference of real parts and complex parts are below the specified threshold
 obstacle_heading_threshold: 0.45 # Specify the value of the normalized scalar product between obstacle heading and goal heading in order to take them (obstacles) into account for exploration
 viapoints_all_candidates: True # If true, all trajectories of different topologies are attached to the set of via-points, otherwise only the trajectory sharing the same one as the initial/global plan is attached (no effect in test_optim_node).
 max_ratio_detours_duration_best_duration: 3.0 # Detours are discarted if their execution time / the execution time of the best teb is > this. 
 visualize_hc_graph: False # Visualize the graph that is created for exploring new homotopy classes
 

 # Recovery
 shrink_horizon_backup: True # Allows the planner to shrink the horizon temporarily (50%) in case of automatically detected issues.
 oscillation_recovery: True # Try to detect and resolve oscillations between multiple solutions in the same equivalence class (robot frequently switches between left/right/forward/backwards).

# Divergence Detection
 divergence_detection_enable: False # True to enable divergence detection.
 divergence_detection_max_chi_squared: 10.0 # Maximum acceptable Mahalanobis distance above which it is assumed that the optimization diverged.

# Deprecated Parameters
#  shrink_horizon_min_duration: 10        # deprecated
#  oscillation_v_eps: 0.1                 # deprecated
#  oscillation_omega_eps: 0.1             # deprecated
#  oscillation_recovery_min_duration: 10  # deprecated
#  oscillation_filter_duration: 10        # deprecated
#  max_samples: 500                       # deprecated
#  simple_exploration: False              # deprecated If true, distinctive trajectories are explored using a simple left-right approach (pass each obstacle on the left or right side) for path generation, otherwise sample possible roadmaps randomly in a specified region between start and goal. 
#  global_plan_prune_distance: 1          # deprecated
#  complete_global_plan: True             # deprecated